name: ahouane_client
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  ahouane_common: 
    path: ../common
  grpc:
    path: ../grpc-dart
  interpolation: ^1.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
