name: ahouane_microservice
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  ahouane_common:
    path: ../common
  rxdart: ^0.24.0
  uuid: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
