name: ahouane_server
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  ahouane_common:
    path: ../common
  ahouane_microservice:
    path: ../microservice
  ahouane_client:
    path: ../client
  csv: ^4.0.3
  dbcrypt: ^1.0.0
  mongo_dart: any
  enough_mail: any
  liquid_engine: ^0.1.2
  secure_random: ^1.0.1
  rxdart: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
