name: protobuf
version: 1.1.3
description: >-
  Runtime library for protocol buffers support.
  Use https://pub.dev/packages/protoc_plugin to generate dart code for your '.proto' files.
homepage: https://github.com/dart-lang/protobuf

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  fixnum: any

dev_dependencies:
  test: '>=1.2.0'
  benchmark_harness: any
  js: any
  pedantic: ^1.9.2
