name: ahouane_common
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  grpc:
    path: ../grpc-dart
  logger: any
  fixnum: any
  xml: any
  optional: ^4.0.1
  intl: ^0.16.1
  universal_io: any
  yaml: any
  uuid: any
  convert: any
  protobuf: 
    path: ../protobuf/protobuf/
  sprintf: ^5.0.0

dev_dependencies:
  pedantic: ^1.8.0
